language: go
sudo: required
services:
  - docker
script:
  - make test
notifications:
  slack:
    rooms:
      secure: 3bhCYkGphXH0L0ktzTZ9/WtOlql7zvlb4INklwxTD0AlxNn0VDkLQp9AOOx6y5/7qguc5qOvdQJ26I/exKxiAVmz3e+X1qmMLdP2dM2MA3ZXf5v4g/IpF788sSX1nA3v3aGkN9NXlwNHUeLzA2hpu9ur26TWQlk99WDgHnIRgDsnH4zyKmebmgpEXeEWsqIumc0Qhw/wpFVVRIowhGHCGGUDGN9JojqQliO5J4xvmXtIm3LJ1DEXNLdKtNbXvjFjAt3hhOlDzEAcXSPxvcto1uy1IKo/n80CpRAfmt/kFuEu8Xh9sQeXFLYuGSCNsgCANi5qWN1ZRdu5QkBZCw/5zmSsXw8E2g3b8lJCjC9yuz3+jxsX6DfFloH0kKlMicyZwFFW+InoabsARaMIhlDS6smkd0HFL0nERHYqmzgEU1VeyIKq0w4FoCrf4tK5oDqCfqm5gkWb7OVTueODNCKl1CSxUSV4OoQnGj9PD+D9D84VESPAMCynOf5nIoafV8AbS1IkBcLsXGrjBkhEgH7deOCZ5FeXp5tKVz7n6TkhHnQdXDBECKAxY6o7NgDURwnuD/xPPSS+x3TfPil6h5u5ecvfNx3RBvndSFTTSpWxQ2FUqAR/W1jkFWNNM2gBVMaIhit3nRqbCfhAoavGrNfHuo7hojqVKFtuFQtxUeoc1E8=
